#!/bin/bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
COMMAND="${1:-all}"

OPENCODE_PUBLIC_HOST="${OPENCODE_PUBLIC_HOST:-8.153.37.206}"
OPENCODE_PERMISSION_MODE="${OPENCODE_PERMISSION_MODE:-deferred-review}"
OPENCODE_BACKEND_SERVER_PORT="${OPENCODE_BACKEND_SERVER_PORT:-4096}"

export NO_PROXY="127.0.0.1,localhost,::1,${OPENCODE_PUBLIC_HOST}${NO_PROXY:+,${NO_PROXY}}"
export no_proxy="127.0.0.1,localhost,::1,${OPENCODE_PUBLIC_HOST}${no_proxy:+,${no_proxy}}"

export OPENCODE_CORS_ORIGINS="${OPENCODE_CORS_ORIGINS:-http://${OPENCODE_PUBLIC_HOST}:3000}"
export OPENCODE_BACKEND_SERVER_HOST="${OPENCODE_BACKEND_SERVER_HOST:-${OPENCODE_PUBLIC_HOST}}"
export OPENCODE_BACKEND_SERVER_PORT
export OPENCODE_PERMISSION_MODE

exec bash "${ROOT_DIR}/start-opencode.sh" "${COMMAND}"
